language: python

cache: pip

python:
  - "3.6"

before_install:
  - sudo apt-get install -y pandoc pandoc-citeproc texlive

addons:
  apt:
    update: true

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
