# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./data
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install pandoc & texlive
          command: |
            sudo apt-get update
            sudo apt-get install pandoc pandoc-citeproc texlive

      # TODO write and run tests with https://pytest.org
      - run:
          name: run tests
          command: |
            . venv/bin/activate
      #      pytest

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build and push Docker image
          command: |
            tag="$(echo $CIRCLE_TAG)"
            tag=${tag#"v"}
            docker build -t maehr/typademic:${tag} -t maehr/typademic:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push maehr/typademic:latest
            docker push maehr/typademic:${tag}

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
