# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install python3
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y python3-minimal python3-venv python-pip

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./data
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install pandoc & texlive
          command: |
            DEBIAN_FRONTEND=noninteractive apt-get install -y pandoc pandoc-citeproc texlive

      # TODO write and run tests with https://pytest.org
      - run:
          name: run tests
          command: |
            . venv/bin/activate
      #      pytest --cov=./
      #      codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
  deploy:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install curl and docker
          command: |
            apt-get update
            apt-get install -y docker.io systemd
            systemctl start docker
            systemctl enable docker

      - run:
          name: Build and push Docker image
          command: |
            export tag="$(echo $CIRCLE_TAG)"
            export tag=${tag#"v"}
            docker build -t maehr/typademic:${tag} -t maehr/typademic:latest .
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push maehr/typademic:${tag}
            docker push maehr/typademic:latest

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
