# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/app

    steps:
      - checkout

      - run:
          name: install python3
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y python3-minimal python3-venv python-pip

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./data
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install pandoc & texlive
          command: |
            DEBIAN_FRONTEND=noninteractive apt-get install -y texlive wget
            wget https://github.com/jgm/pandoc/releases/download/2.7.1/pandoc-2.7.1-1-amd64.deb
            dpkg -i pandoc-2.7.1-1-amd64.deb

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install coverage codecov pytest pytest-cov
            py.test --cov=typademic tests/
            coverage html --directory=test-reports
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports


workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
